#define BITCOIN_ELLIPTIC_CURVE "secp256k1"
#define BITCOIN_PATH_PURPOSE 0
#define BITCOIN_PATH_COIN_TYPE 0
#define BITCOIN_PATH_ACCOUNT 0
#define BITCOIN_MAXIMUM_ADDRESS_LENGTH 39
#define BITCOIN_ADDRESS_VERSION_BYTE 0
#define BITCOIN_HD_MASTER_SEED_SIZE 64

#define DOGE_PATH_PURPOSE 0
#define DOGE_PATH_COIN_TYPE 3
#define DOGE_PATH_ACCOUNT 0
#define DOGE_ADDRESS_VERSION_BYTE 0x1e

#define ETHEREUM_CLASSIC_HD_ELLIPTIC_CURVE BITCOIN_ELLIPTIC_CURVE
#define ETHEREUM_CLASSIC_PATH_PURPOSE 44
#define ETHEREUM_CLASSIC_PATH_COIN_TYPE 61
#define ETHEREUM_CLASSIC_PATH_ACCOUNT 0
#define ETHEREUM_CLASSIC_ADDRESS_BYTES 20
#define ETHEREUM_CLASSIC_ADDRESS_LENGTH 2*ETHEREUM_CLASSIC_ADDRESS_BYTES+3

#define ETHEREUM_HD_ELLIPTIC_CURVE BITCOIN_ELLIPTIC_CURVE
#define ETHEREUM_PATH_PURPOSE 44
#define ETHEREUM_PATH_COIN_TYPE 60
#define ETHEREUM_PATH_ACCOUNT 0
#define ETHEREUM_ADDRESS_BYTES 20
#define ETHEREUM_ADDRESS_LENGTH 2*ETHEREUM_ADDRESS_BYTES+3

#define NOSTR_PATH_PURPOSE 44
#define NOSTR_PATH_COIN_TYPE 1237
#define NOSTR_PATH_ACCOUNT 0
#define NOSTR_PATH_CHANGE 0
#define NOSTR_PATH_INDEX 0
#define NOSTR_PUBLIC_KEY_SIZE 32
#define NOSTR_PUBLIC_ADDRESS_HRP_SIZE 4+2

#define MONERO_PRIVATE_SPEND_KEY_LENGTH 32
#define MONERO_PUBLIC_SPEND_KEY_LENGTH 32
#define MONERO_PUBLIC_VIEW_KEY_LENGTH 32
#define MONERO_PUBLIC_KEYS_LENGTH MONERO_PUBLIC_SPEND_KEY_LENGTH+MONERO_PUBLIC_VIEW_KEY_LENGTH
#define MONERO_MAXIMUM_ADDRESS_LENGTH 128
#define MONERO_MAINNET_MAGIC_BYTE 18
